### PR TITLE
docs: fix broken link to `podman-push.1.md`

### PR DESCRIPTION
**Pull request by vladdoster**
Screenshot 2023-02-17 at 18 16 33

### CODE REVIEW

**Comment by vladdoster** [comment]
Huh, this is the correct link, but for some reason, the `podman-push.md` has not been generated. Even the official docs redirect to GitHub is broken.

Maybe the link should point to <https://docs.podman.io/en/latest/markdown/podman-push.1.html>?

---

https://user-images.githubusercontent.com/10052309/219821053-25ec0999-07fa-477c-b146-6d3beba98ac4.mov

**Comment by nullr0ute** [comment]
> Huh, this is the correct link, but for some reason, the `podman-push.md` has not been generated. Even the official docs redirect to GitHub is broken.
> 
> Maybe the link should point to https://docs.podman.io/en/latest/markdown/podman-push.1.html?

Maybe the bug should be with podman to get the podman-push docs generated?

**Comment by vladdoster** [comment]
> > Huh, this is the correct link, but for some reason, the `podman-push.md` has not been generated. Even the official docs redirect to GitHub is broken.
> > Maybe the link should point to https://docs.podman.io/en/latest/markdown/podman-push.1.html?
> 
> Maybe the bug should be with podman to get the podman-push docs generated?

@nullr0ute,

Indeed, that is an issue as well. I'll open an issue.

Regardless, this PR is still valid due to `master` branch renamed to `main`.

**Comment by nullr0ute** [comment]
> Regardless, this PR is still valid due to `master` branch renamed to `main`.

Merged, feel free to drop a comment here with the other bug or a note when it's fixed. Thanks.

**Pull request merged**
